version: "3"
services:
  postgres_wikimusic:
    container_name: postgres_wikimusic
    image: postgres:15.5
    environment:
      - POSTGRES_USER=wikimusic_admin
      - POSTGRES_PASSWORD=wikimusic_admin
      - POSTGRES_DB=wikimusic_database

    ports:
      - "55432:5432"
    restart: always
    
  cache_wikimusic:
    container_name: cache_wikimusic
    image: redis:7.2.4
    restart: always
    ports:
      - "63379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    
volumes:
  cache:
    driver: local
