ALTER TABLE artists ADD COLUMN views INT NOT NULL DEFAULT 0;
ALTER TABLE forum_categories ADD COLUMN views INT NOT NULL DEFAULT 0;
ALTER TABLE forum_pages ADD COLUMN views INT NOT NULL DEFAULT 0;
ALTER TABLE genres ADD COLUMN views INT NOT NULL DEFAULT 0;
ALTER TABLE songs ADD COLUMN views INT NOT NULL DEFAULT 0;
