name: "on pull request - byggsteg"
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  on-pull-request-byggsteg:
    runs-on: ubuntu-latest
    steps:              
      - name: "trigger build, test and hackage bundle at byggsteg"
        run: |
           curl 'https://byggsteg.jointhefreeworld.org/api/jobs/submit' \
               -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
               -H 'Authorization: Basic ${{secrets.BYGGSTEG_KEY}}' \
               --data-raw 'project=wikimusic-api&clone-url=https%3A%2F%2Fgithub.com%2Fjjba23%2Fwikimusic-api&branch-name=trunk&task=stack-test'

